### ISSUE TITLE
All lists empty in Cartoon category

### ISSUE THREAD

**Issue by huggums537** [Twoure/KissNetwork.bundle#65]
The Cartoon category is the only one with a problem in Plex. All the other Categories work just fine. It happened after an update and I lost all my bookmarks. Interestingly enough, the Cartoon category is the only one I use and the only one I had saved any bookmarks with. I was wondering if maybe it had something to do with a difference in domain names since I watch it online at kisscartoon.io, but the preferences have it listed as kisscartoon.se. However, all the other categories have different domain names than the one I watch online and they don't seem to be affected...

**Comment by Twoure** [comment]
Please review [Reporting an issue](https://github.com/Twoure/KissNetwork.bundle/wiki/Reporting%20an%20issue), then add the appropriate logs/info to your original post.

**Comment by zeltordaeon** [comment]
**KissNetwork Version:** 1.2.9 dev
**Plex Media Server:** Version 3.2.1
**OS:** Windows 10
**Plex Client:** Web
**Steps to Reproduce:**
1. Launch **Plex Media Server**
2. Click **Channels** under _Online Content_
3. Click **KissNetwork**
4. Click **Cartoon**
5. Click **All**

**Error Message Received:** "This channel is not responding."
[Logs.zip](https://github.com/Twoure/KissNetwork.bundle/files/1070481/Logs.zip)
~_screenshot.png_~ _(redacted by @Twoure)_ 


**Chrome Console Network Response for directory?category=all**
`<?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="AttributeError: 'NoneType' object has no attribute 'text'">
  <Traceback>Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-995f1dead\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
  File "C:\Users\Lucas\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Code\__init__.py", line 744, in DirectoryList
    title2 = u'{} | Not Yet Aired'.format(item_title)
  File "C:\Users\Lucas\AppData\Local\Plex Media Server\Plug-ins\KissNetwork.bundle\Contents\Services\Shared Code\knetwork.pys", line 152, in ElementFromURL
    return HTML.ElementFromString(self.Request(url, headers, follow_redirects=follow_redirects, method='GET').text)
AttributeError: 'NoneType' object has no attribute 'text'
</Traceback>
</Response>
`

**Comment by Twoure** [comment]
@zeltordaeon 
I removed your screenshot because it included your Plex Token.
